#!/usr/bin/env bash
# lint.sh — Run clang-tidy over the project.
# Requires a compile_commands.json (generated by CMake with CMAKE_EXPORT_COMPILE_COMMANDS=ON).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-${REPO_ROOT}/build}"

if [[ ! -f "${BUILD_DIR}/compile_commands.json" ]]; then
    echo "Error: compile_commands.json not found in ${BUILD_DIR}."
    echo "Run CMake with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON first."
    exit 1
fi

find "${REPO_ROOT}/src" "${REPO_ROOT}/include" \
    \( -name "*.cpp" -o -name "*.hpp" \) \
    | xargs clang-tidy \
        -p "${BUILD_DIR}" \
        --config-file="${REPO_ROOT}/.clang-tidy" \
        "$@"

echo "clang-tidy complete."
